In [2]:
import numpy as np
x=np.arange(1,17)
#ques.1
print(x[7:12])
print(x[-9:-4])
#ques2
print(x[x%2==0])
#ques.3
print(x[::4])

[ 8  9 10 11 12]
[ 8  9 10 11 12]
[ 2  4  6  8 10 12 14 16]
[ 1  5  9 13]
