In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets

# Loading Dataset

In [2]:
digits = datasets.load_digits()

In [3]:
x=digits.data
y=digits.target

# Test Train Splitt

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, \
                                                   y, \
                                                   test_size = 0.3, \
                                                   random_state = 0)

# Training

In [7]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

# Prediction

In [9]:
y_pred=classifier.predict(X_test)

In [39]:
from sklearn import metrics

print('Confussion Matrics: \n\n', metrics.confusion_matrix(y_test, y_pred))

print('\n\nAccuracy_score: ', metrics.accuracy_score(y_test, y_pred))

print('\n\nClassification Report: \n\n', metrics.classification_report(y_test, y_pred))

Confussion Matrics: 

 [[45  0  0  0  0  0  0  0  0  0]
 [ 0 47  0  0  0  0  2  0  3  0]
 [ 0  0 51  2  0  0  0  0  0  0]
 [ 0  0  1 52  0  0  0  0  0  1]
 [ 0  0  0  0 48  0  0  0  0  0]
 [ 0  1  0  0  0 55  1  0  0  0]
 [ 0  1  0  0  0  0 59  0  0  0]
 [ 0  1  0  1  1  0  0 50  0  0]
 [ 0  3  1  0  0  0  0  0 55  2]
 [ 0  0  0  1  0  1  0  0  2 53]]


Accuracy_score:  0.9537037037037037


Classification Report: 

              precision    recall  f1-score   support

          0       1.00      1.00      1.00        45
          1       0.89      0.90      0.90        52
          2       0.96      0.96      0.96        53
          3       0.93      0.96      0.95        54
          4       0.98      1.00      0.99        48
          5       0.98      0.96      0.97        57
          6       0.95      0.98      0.97        60
          7       1.00      0.94      0.97        53
          8       0.92      0.90      0.91        61
          9       0.95      0.93      0.94       